#!/bin/bash
# To run the container in the background in a “detached” mode in detached mode -d
# To expose a container’s internal port, start the container with -p
docker run -d -p 5000:80 --name overlord nginx
